---
- name: Disallow root SSH access
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: restart sshd

- name: Disallow password authentication
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart sshd

- name: Install fail2ban
  action: apt pkg=fail2ban state=installed

- name: Configure fail2ban
  template: src=jail.conf.j2 dest=/etc/fail2ban/jail.conf mode=0644

- name: Restart fail2ban service, ensure it's enabled.
  service: name=fail2ban state=restarted enabled=yes